#ifndef SYNTAX_H
#define SYNTAX_H

#define bool_key_word       "bool"
#define color_key_word      "color"
#define error_key_word      "error"
#define float_key_word      "float"
#define int_key_word        "int"
#define string_key_word     "string"
#define var_key_word        "var"
#define void_key_word       "void"

#define null_key_word       "null"
#define none_key_word       "none"

#define true_key_word       "true"
#define false_key_word      "false"

#define new_operator        "new"
#define delete_operator     "delete"

#define this_key_word       "this"

#define public_tocken       "public"
#define private_tocken      "private"
#define protected_tocken    "protected"
#define static_tocken       "static"

#define chevron_open_tocken     "<"
#define chevron_close_tocken    ">"
#define break_tocken            "break"
#define case_tocken             "case"
#define catch_tocken            "catch"
#define class_tocken            "class"
#define continue_tocken         "continue"
#define default_tocken          "default"
#define else_tocken             "else"
#define enum_tocken             "enum"
#define for_tocken              "for"
#define if_tocken               "if"
#define load_tocken             "load"
#define print_tocken            "print"
#define property_tocken         "property"
#define return_tocken           "return"
#define switch_tocken           "switch"
#define throw_tocken            "throw"
#define try_tocken              "try"
#define yield_tocken            "yield"
#define while_tocken            "while"

#define back_slash_operator         "\\"

#define copy_operator               "="
#define deep_copy_operator          ":="
#define adress_operator             "@"
#define const_ref_operator          "$"
#define in_operator                 "in"
#define block_open_operator         "{"
#define block_close_operator        "}"
#define block_operator              "{}"
#define parenthesis_open_operator   "("
#define parenthesis_close_operator  ")"
#define parenthesis_operator        "()"
#define bracket_open_operator       "["
#define bracket_close_operator      "]"
#define bracket_operator            "[]"
#define logical_not_operator        "!"
#define add_operator                "+"
#define sub_operator                "-"
#define mult_operator               "*"
#define div_operator                "/"
#define mod_operator                "%"
#define lt_operator                 "<"
#define gt_operator                 ">"
#define lteq_operator               "<="
#define gteq_operator               ">="
#define eq_operator                 "=="
#define ne_operator                 "!="
#define logical_and_operator        "&"
#define logical_or_operator         "|"
#define comma_operator              ","
#define semicolon_operator          ";"

#endif // SYNTAX_H
